"use client";
import { Resume, FormattedDescription, SocialLinks } from "./shared";

export function MinimalEdgePreview({ resume }: { resume: Resume }) {
  const slate = "#475569", dark = "#0f172a", light = "#94a3b8", border = "#e2e8f0";
  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-7"><h2 className="mb-3 border-b pb-2 text-[10px] font-semibold uppercase tracking-[0.3em]" style={{ color: slate, borderColor: border }}>{title}</h2>{children}</section>;
  return <div className="overflow-hidden rounded-lg bg-white shadow-2xl" style={{ fontFamily: "'Work Sans', 'Segoe UI', sans-serif", color: slate }}>
    <div className="p-8">
      <header className="mb-9"><h1 className="text-4xl font-light leading-none tracking-tight" style={{ color: dark }}>{resume.name || "Your Name"}</h1><p className="mt-3 text-xs font-medium uppercase tracking-[0.28em]" style={{ color: slate }}>{resume.title || "Professional Title"}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-1 text-[10px]" style={{ color: light }}>{resume.email && <span>{resume.email}</span>}{resume.phone && <span>{resume.phone}</span>}{resume.address && <span>{resume.address}</span>}{resume.nationality && <span>{resume.nationality}</span>}</div>{resume.social && <div className="mt-2"><SocialLinks social={resume.social} color={light} size="xs" /></div>}</header>
      {resume.summary && <section className="mb-8 border-l pl-5" style={{ borderColor: slate }}><FormattedDescription text={resume.summary} color={slate} mutedColor={slate} size="sm" /></section>}
      {resume.experience.length > 0 && <Section title="Experience">{resume.experience.map(e => <article key={e.id} className="mb-6 last:mb-0"><div className="flex items-start justify-between gap-5"><div><h3 className="text-sm font-semibold" style={{ color: dark }}>{e.position}</h3><p className="mt-0.5 text-xs">{e.company}{e.location && ` / ${e.location}`}</p></div><span className="shrink-0 text-[10px] uppercase tracking-wider" style={{ color: light }}>{e.duration}</span></div>{e.description && <div className="mt-2"><FormattedDescription text={e.description} color={slate} mutedColor={slate} /></div>}{e.achievements && <FormattedDescription text={e.achievements} color={slate} mutedColor={light} />}</article>)}</Section>}
      {resume.education.length > 0 && <Section title="Education"><div className="grid grid-cols-2 gap-x-8 gap-y-4">{resume.education.map(edu => <article key={edu.id}><div className="flex justify-between gap-2"><h3 className="text-sm font-semibold" style={{ color: dark }}>{edu.school}</h3><span className="text-[10px]" style={{ color: light }}>{edu.year}</span></div><p className="mt-1 text-xs">{edu.degree}{edu.field && ` / ${edu.field}`}</p>{edu.honors && <p className="text-[10px]" style={{ color: light }}>{edu.honors}</p>}</article>)}</div></Section>}
      {resume.skills.length > 0 && <Section title="Capabilities"><div className="grid grid-cols-3 gap-x-6 gap-y-3">{resume.skills.map(s => <div key={s.id} className="border-b pb-1.5" style={{ borderColor: border }}><p className="text-xs font-medium" style={{ color: dark }}>{s.name}</p><p className="text-[9px] uppercase tracking-wider" style={{ color: light }}>{[s.category, s.level].filter(Boolean).join(" / ")}</p></div>)}</div></Section>}
      {resume.projects.length > 0 && <Section title="Selected Work"><div className="grid grid-cols-2 gap-6">{resume.projects.map(p => <article key={p.id}><div className="flex justify-between gap-2"><h3 className="text-sm font-semibold" style={{ color: dark }}>{p.name}</h3>{p.startDate && <span className="text-[9px]" style={{ color: light }}>{p.startDate}—{p.endDate || "Now"}</span>}</div>{p.role && <p className="mt-0.5 text-[10px] uppercase tracking-wider">{p.role}</p>}{p.description && <div className="mt-1"><FormattedDescription text={p.description} color={slate} mutedColor={slate} /></div>}{p.tech && <p className="mt-1 text-[10px]" style={{ color: light }}>{p.tech}</p>}</article>)}</div></Section>}
      {resume.certifications.length > 0 && <Section title="Credentials"><div className="grid grid-cols-2 gap-3">{resume.certifications.map(c => <p key={c.id} className="text-xs"><span className="font-medium" style={{ color: dark }}>{c.name}</span>{c.issuer && <span> / {c.issuer}</span>}{c.date && <span style={{ color: light }}> / {c.date}</span>}</p>)}</div></Section>}
      {resume.achievements.length > 0 && <Section title="Recognition">{resume.achievements.map(a => <p key={a.id} className="mb-1 text-xs">{a.description}</p>)}</Section>}
      <div className="grid grid-cols-3 gap-7">
        {resume.languages.length > 0 && <Section title="Languages">{resume.languages.map(l => <p key={l.id} className="text-xs">{l.name} <span style={{ color: light }}>/ {l.proficiency}</span></p>)}</Section>}
        {resume.interests.length > 0 && <Section title="Interests"><p className="text-xs">{resume.interests.map(i => i.name).join(" / ")}</p></Section>}
        {resume.references.length > 0 && <Section title="References">{resume.references.map(r => <p key={r.id} className="mb-1 text-xs"><span style={{ color: dark }}>{r.name}</span>{r.company && ` / ${r.company}`}</p>)}</Section>}
      </div>
    </div>
  </div>;
}
