"use client";

import type { Resume } from "@/types/resume";

/**
 * Realistic sample resume rendered inside the template gallery previews.
 *
 * This data exists ONLY to showcase each template's design — it is never
 * written into the user's resume. Volume is intentionally generous so
 * multi-section templates genuinely overflow into a second page, which the
 * full preview uses to demonstrate page navigation.
 */
export const GALLERY_SAMPLE_RESUME: Resume = {
  name: "Jordan Rivera",
  title: "Senior Platform Engineer",
  email: "jordan.rivera@example.com",
  phone: "+1 (415) 555-0184",
  address: "San Francisco, CA",
  nationality: "American",
  pronouns: "they/them",
  summary:
    "Platform and infrastructure engineer with 10 years of experience designing cloud-native systems that serve millions of users. Specializes in Kubernetes, developer experience, and reliability engineering. Led migrations that cut infrastructure cost by 38% and reduced mean time to recovery from hours to minutes.",
  social: {
    linkedin: "linkedin.com/in/jordanrivera",
    github: "github.com/jordanrivera",
    website: "jordanrivera.dev",
    twitter: "",
    portfolio: "jordanrivera.dev/work",
    stackoverflow: "stackoverflow.com/users/jordanrivera",
  },
  experience: [
    {
      id: "gx-1",
      company: "Northwind Labs",
      position: "Staff Platform Engineer",
      location: "San Francisco, CA",
      employmentType: "Full-time",
      industry: "Technology",
      startDate: "2021-06",
      endDate: "",
      current: true,
      duration: "2021 – Present",
      description:
        "Lead the internal developer platform serving 400+ engineers across 60 product teams. Own the Kubernetes control plane, CI/CD foundations, and golden-path observability.",
      achievements: "Cut infrastructure cost 38% YoY; reduced MTTR from 4 hours to 12 minutes.",
      techUsed: "Kubernetes, Terraform, Go, AWS, Argo CD, Datadog",
      bulletPoints: [
        "Designed a multi-tenant Kubernetes platform now running 1,200+ workloads in production",
        "Introduced GitOps delivery with Argo CD, cutting deploy time from 25 minutes to under 4",
        "Built an internal CLI adopted by 300+ engineers that reduced environment setup to one command",
        "Grew the platform team from 2 to 9 engineers and established an on-call rotation",
      ],
    },
    {
      id: "gx-2",
      company: "Meridian Systems",
      position: "Senior Software Engineer",
      location: "Seattle, WA",
      employmentType: "Full-time",
      industry: "Enterprise Software",
      startDate: "2017-03",
      endDate: "2021-05",
      current: false,
      duration: "2017 – 2021",
      description:
        "Backend engineer on the payments platform processing $2B annually. Owned service decomposition, database sharding, and the incident response runbooks.",
      achievements: "Scaled checkout to 99.99% uptime; sharded PostgreSQL to support 10× volume.",
      techUsed: "Go, PostgreSQL, Kafka, AWS, Redis",
      bulletPoints: [
        "Led migration from a monolith to 14 microservices without a single customer-facing incident",
        "Sharded the core PostgreSQL database to support 10× transaction volume",
        "Cut p95 checkout latency from 900 ms to 210 ms through caching and query optimization",
      ],
    },
    {
      id: "gx-3",
      company: "Brightpath Analytics",
      position: "Software Engineer",
      location: "Portland, OR",
      employmentType: "Full-time",
      industry: "Data Analytics",
      startDate: "2014-06",
      endDate: "2017-02",
      current: false,
      duration: "2014 – 2017",
      description:
        "Full-stack engineer on the data pipeline team, building ingestion and real-time dashboards for enterprise customers.",
      achievements: "Doubled pipeline throughput; built the first real-time dashboard product.",
      techUsed: "Python, React, Spark, Elasticsearch",
      bulletPoints: [
        "Rebuilt the ingestion pipeline in Spark, doubling throughput and cutting costs by 45%",
        "Shipped the company's first real-time analytics dashboard, adopted by 120+ customers",
      ],
    },
    {
      id: "gx-4",
      company: "CloudNine",
      position: "Software Engineer Intern",
      location: "Austin, TX",
      employmentType: "Internship",
      industry: "Cloud Infrastructure",
      startDate: "2013-05",
      endDate: "2013-08",
      current: false,
      duration: "Summer 2013",
      description: "Intern on the compute team; automated instance lifecycle and wrote internal tooling.",
      achievements: "",
      techUsed: "Python, Linux, AWS",
      bulletPoints: ["Automated stale-instance cleanup, recovering 12% of idle capacity"],
    },
  ],
  education: [
    {
      id: "ge-1",
      school: "Carnegie Mellon University",
      degree: "M.S.",
      field: "Computer Science",
      year: "2016",
      gpa: "3.9",
      minor: "",
      honors: "Graduate Research Fellowship",
      activities: "Distributed Systems Lab",
      location: "Pittsburgh, PA",
    },
    {
      id: "ge-2",
      school: "University of Texas at Austin",
      degree: "B.S.",
      field: "Computer Engineering",
      year: "2014",
      gpa: "3.8",
      minor: "Mathematics",
      honors: "Dean's List, Tau Beta Pi",
      activities: "ACM Programming Team",
      location: "Austin, TX",
    },
  ],
  skills: [
    { id: "gs-1", name: "Kubernetes", level: "Expert", category: "Infrastructure", years: "6" },
    { id: "gs-2", name: "Go", level: "Expert", category: "Languages", years: "7" },
    { id: "gs-3", name: "TypeScript", level: "Expert", category: "Languages", years: "8" },
    { id: "gs-4", name: "AWS", level: "Expert", category: "Cloud", years: "9" },
    { id: "gs-5", name: "Terraform", level: "Advanced", category: "Infrastructure", years: "6" },
    { id: "gs-6", name: "PostgreSQL", level: "Advanced", category: "Databases", years: "8" },
    { id: "gs-7", name: "Docker", level: "Expert", category: "Infrastructure", years: "8" },
    { id: "gs-8", name: "Argo CD", level: "Advanced", category: "CI/CD", years: "4" },
    { id: "gs-9", name: "Kafka", level: "Advanced", category: "Data", years: "5" },
    { id: "gs-10", name: "React", level: "Advanced", category: "Frontend", years: "7" },
    { id: "gs-11", name: "Datadog", level: "Advanced", category: "Observability", years: "5" },
    { id: "gs-12", name: "gRPC", level: "Intermediate", category: "Networking", years: "4" },
  ],
  projects: [
    {
      id: "gp-1",
      name: "Helmless",
      description:
        "Open-source Kubernetes manifest generation tool that removes Helm templating complexity for teams adopting GitOps.",
      tech: "Go, Kubernetes, YAML",
      link: "github.com/jordanrivera/helmless",
      startDate: "2022-01",
      endDate: "2023-04",
      role: "Creator & Maintainer",
      teamSize: "2",
      status: "Completed",
      bulletPoints: ["4,100 GitHub stars; adopted by 40+ engineering organizations"],
    },
    {
      id: "gp-2",
      name: "Platform Observability Console",
      description:
        "Unified internal console aggregating metrics, traces, and deploy state so engineers can troubleshoot without switching between six tools.",
      tech: "React, Go, Datadog, ClickHouse",
      link: "",
      startDate: "2022-03",
      endDate: "2023-02",
      role: "Tech Lead",
      teamSize: "4",
      status: "Completed",
      bulletPoints: ["Reduced average troubleshooting time from 38 minutes to 9 minutes"],
    },
    {
      id: "gp-3",
      name: "Event Bus Migration",
      description:
        "Company-wide migration from a self-managed message queue to managed Kafka with exactly-once semantics and replay tooling.",
      tech: "Kafka, Go, AWS MSK",
      link: "",
      startDate: "2020-01",
      endDate: "2020-11",
      role: "Lead Engineer",
      teamSize: "3",
      status: "Completed",
      bulletPoints: ["Zero-downtime migration across 22 services over 11 months"],
    },
    {
      id: "gp-4",
      name: "CLI Bootstrapper",
      description:
        "Internal tool that scaffolds a service with CI, observability, and staging environments pre-configured from a single command.",
      tech: "Go, Cobra, GitHub Actions",
      link: "",
      startDate: "2023-05",
      endDate: "",
      role: "Maintainer",
      teamSize: "1",
      status: "Ongoing",
      bulletPoints: ["Onboards a new service in under 90 seconds end-to-end"],
    },
  ],
  certifications: [
    {
      id: "gc-1",
      name: "AWS Certified Solutions Architect – Professional",
      issuer: "Amazon Web Services",
      date: "2023-03",
      link: "",
      description: "Advanced architecture on AWS, including multi-account and hybrid designs.",
      expiryDate: "2026-03",
      skills: "AWS, Cloud Architecture",
    },
    {
      id: "gc-2",
      name: "Certified Kubernetes Administrator (CKA)",
      issuer: "Cloud Native Computing Foundation",
      date: "2022-08",
      link: "",
      description: "Production-grade Kubernetes cluster administration.",
      expiryDate: "2025-08",
      skills: "Kubernetes, Linux",
    },
    {
      id: "gc-3",
      name: "HashiCorp Certified: Terraform Associate",
      issuer: "HashiCorp",
      date: "2021-11",
      link: "",
      description: "Infrastructure as code with Terraform across cloud providers.",
      expiryDate: "2024-11",
      skills: "Terraform, IaC",
    },
    {
      id: "gc-4",
      name: "Google Cloud Professional Cloud Architect",
      issuer: "Google Cloud",
      date: "2021-05",
      link: "",
      description: "Designing and managing GCP solutions.",
      expiryDate: "2024-05",
      skills: "GCP, Cloud Architecture",
    },
  ],
  achievements: [
    {
      id: "ga-1",
      title: "Infrastructure Innovation Award",
      description: "Company-wide award for the developer platform that transformed engineering velocity.",
      date: "2023-01",
      issuer: "Northwind Labs",
    },
    {
      id: "ga-2",
      title: "Speaker, KubeCon North America",
      description: "Presented a talk on GitOps at scale to an audience of 3,000+.",
      date: "2022-10",
      issuer: "CNCF",
    },
    {
      id: "ga-3",
      title: "Gold Award — Internal Hackathon",
      description: "Won with a prototype that cut CI minutes by 60% using build caching.",
      date: "2021-12",
      issuer: "Meridian Systems",
    },
    {
      id: "ga-4",
      title: "Open Source Contributor",
      description: "Regular contributor to the Kubernetes and Argo CD communities.",
      date: "2020",
      issuer: "CNCF",
    },
  ],
  languages: [
    { id: "gl-1", name: "English", proficiency: "Native" },
    { id: "gl-2", name: "Spanish", proficiency: "Professional" },
    { id: "gl-3", name: "Portuguese", proficiency: "Conversational" },
  ],
  interests: [
    { id: "gi-1", name: "Open Source Infrastructure" },
    { id: "gi-2", name: "Technical Writing" },
    { id: "gi-3", name: "Trail Running" },
  ],
  references: [
    {
      id: "gr-1",
      name: "Aisha Patel",
      company: "Northwind Labs",
      position: "VP of Engineering",
      email: "aisha.patel@example.com",
      phone: "+1 (415) 555-0192",
    },
    {
      id: "gr-2",
      name: "Daniel Okafor",
      company: "Meridian Systems",
      position: "Principal Engineer",
      email: "daniel.okafor@example.com",
      phone: "+1 (206) 555-0147",
    },
  ],
  portfolio: [
    {
      id: "gp-5",
      title: "Personal Site",
      description: "Essays on platform engineering and incident postmortems.",
      url: "jordanrivera.dev",
      type: "website",
    },
    {
      id: "gp-6",
      title: "GitHub",
      description: "Open-source projects and contribution history.",
      url: "github.com/jordanrivera",
      type: "github",
    },
  ],
  templateId: "modern-clean",
  careerStage: "working-professional",
  claims: [],
};
