export interface ResumeTemplate {
  id: string;
  name: string;
  description: string;
  preview: string;
  /** Core structural layout family. */
  family: "ats" | "professional" | "executive" | "serif" | "two-column" | "sidebar-left" | "banner" | "compact" | "premium" | "timeline";
  layout: "standard" | "two-column" | "banner" | "sidebar-right" | "compact";
  suggestedFont: string;
  /** Short ATS classification label. */
  atsLabel: string;
  category: string;
  atsRating: number;
  experienceLevel: "Entry" | "Mid" | "Senior" | "Executive";
  suggestedColors: {
    primary: string;
    secondary: string;
    accent: string;
    bg: string;
    text: string;
    muted: string;
    border: string;
    cardBg: string;
    sectionTitle: string;
  };
  recommendedFor?: string;
  /** True if this is a legacy template kept for backward compatibility. Not shown in new gallery by default. */
  legacy?: boolean;
}

export const FONTS = [
  { id: "inter", name: "Inter", family: "'Inter', 'Segoe UI', sans-serif", category: "Sans-serif" },
  { id: "roboto", name: "Roboto", family: "'Roboto', 'Helvetica Neue', sans-serif", category: "Sans-serif" },
  { id: "montserrat", name: "Montserrat", family: "'Montserrat', 'Arial', sans-serif", category: "Sans-serif" },
  { id: "opensans", name: "Open Sans", family: "'Open Sans', 'Segoe UI', sans-serif", category: "Sans-serif" },
  { id: "lato", name: "Lato", family: "'Lato', 'Helvetica Neue', sans-serif", category: "Sans-serif" },
  { id: "poppins", name: "Poppins", family: "'Poppins', 'Segoe UI', sans-serif", category: "Sans-serif" },
  { id: "merriweather", name: "Merriweather", family: "'Merriweather', 'Georgia', serif", category: "Serif" },
  { id: "playfair", name: "Playfair Display", family: "'Playfair Display', 'Georgia', serif", category: "Serif" },
  { id: "garamond", name: "EB Garamond", family: "'EB Garamond', 'Georgia', serif", category: "Serif" },
  { id: "robotoslab", name: "Roboto Slab", family: "'Roboto Slab', 'Georgia', serif", category: "Serif" },
  { id: "worksans", name: "Work Sans", family: "'Work Sans', 'Helvetica Neue', sans-serif", category: "Sans-serif" },
  { id: "sfmono", name: "SF Mono", family: "'SF Mono', 'Menlo', monospace", category: "Monospace" },
  { id: "jakarta", name: "Plus Jakarta Sans", family: "'Plus Jakarta Sans', 'Segoe UI', sans-serif", category: "Sans-serif" },
  { id: "fraunces", name: "Fraunces", family: "'Fraunces', 'Georgia', serif", category: "Serif" },
];

export const COLOR_PALETTES = [
  { id: "navy", name: "Navy Professional", colors: { primary: "#1e3a8a", secondary: "#1e40af", accent: "#2563eb", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#1e3a8a" } },
  { id: "emerald", name: "Emerald Green", colors: { primary: "#047857", secondary: "#059669", accent: "#10b981", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#047857" } },
  { id: "royal", name: "Royal Purple", colors: { primary: "#7c3aed", secondary: "#6d28d9", accent: "#8b5cf6", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#7c3aed" } },
  { id: "crimson", name: "Crimson Red", colors: { primary: "#b91c1c", secondary: "#dc2626", accent: "#ef4444", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#b91c1c" } },
  { id: "ocean", name: "Ocean Blue", colors: { primary: "#0284c7", secondary: "#0ea5e9", accent: "#38bdf8", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#0284c7" } },
  { id: "sunset", name: "Sunset Orange", colors: { primary: "#ea580c", secondary: "#f97316", accent: "#fb923c", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#ea580c" } },
  { id: "slate", name: "Slate Dark", colors: { primary: "#1e293b", secondary: "#334155", accent: "#475569", bg: "#ffffff", text: "#0f172a", muted: "#475569", border: "#cbd5e1", cardBg: "#f1f5f9", sectionTitle: "#1e293b" } },
  { id: "rose", name: "Rose Pink", colors: { primary: "#be123c", secondary: "#e11d48", accent: "#fb7185", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#be123c" } },
  { id: "teal", name: "Teal Modern", colors: { primary: "#0d9488", secondary: "#14b8a6", accent: "#2dd4bf", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#0d9488" } },
  { id: "amber", name: "Amber Warm", colors: { primary: "#b45309", secondary: "#d97706", accent: "#f59e0b", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#b45309" } },
  { id: "indigo", name: "Indigo Depth", colors: { primary: "#4338ca", secondary: "#4f46e5", accent: "#6366f1", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#4338ca" } },
  { id: "lime", name: "Lime Fresh", colors: { primary: "#4d7c0f", secondary: "#65a30d", accent: "#84cc16", bg: "#ffffff", text: "#1f2937", muted: "#4b5563", border: "#d1d5db", cardBg: "#f8fafc", sectionTitle: "#4d7c0f" } },
];

export const TEMPLATES: ResumeTemplate[] = [
  {
    id: "executive",
    name: "Executive",
    description: "Dark banner header with gold accents and serif typography. Designed for senior leadership.",
    preview: "🏛️",
    family: "executive",
    layout: "banner",
    suggestedFont: "garamond",
    atsLabel: "ATS Friendly",
    category: "Executive",
    atsRating: 97,
    experienceLevel: "Executive",
    recommendedFor: "Managers, Directors & C-Suite",
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#1e3a8a",
      accent: "#c9b068",
      bg: "#ffffff",
      text: "#1f2937",
      muted: "#6b7280",
      border: "#e2e8f0",
      cardBg: "#f8fafc",
      sectionTitle: "#0f172a"
    }
  },
  {
    id: "patorbit-modern",
    name: "Tech Two-Column",
    description: "Two-column layout with right sidebar for skills and education. Built for engineers and technical professionals.",
    preview: "⚡",
    family: "two-column",
    layout: "two-column",
    suggestedFont: "jakarta",
    atsLabel: "ATS Friendly",
    category: "Software Engineer",
    atsRating: 98,
    experienceLevel: "Senior",
    recommendedFor: "Software, AI & Tech Professionals",
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#0ea5e9",
      accent: "#2563eb",
      bg: "#ffffff",
      text: "#0f172a",
      muted: "#64748b",
      border: "#e2e8f0",
      cardBg: "#eff6ff",
      sectionTitle: "#2563eb"
    }
  },
  {
    id: "minimal-ats",
    name: "Minimal ATS",
    description: "Maximum ATS readability. Monochrome, zero decoration, predictable single-column flow.",
    preview: "📄",
    family: "ats",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "Maximum ATS",
    category: "ATS Optimized",
    atsRating: 99,
    experienceLevel: "Mid",
    recommendedFor: "Strict ATS Applications & Enterprise Hiring",
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#64748b",
      bg: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
      border: "#e2e8f0",
      cardBg: "#f8fafc",
      sectionTitle: "#64748b"
    }
  },
  {
    id: "modern-clean",
    name: "Professional",
    description: "Clean single-column with centered header. Versatile professional template for any industry.",
    preview: "✨",
    family: "professional",
    layout: "standard",
    suggestedFont: "inter",
    atsLabel: "ATS Optimized",
    category: "Professional",
    atsRating: 98,
    experienceLevel: "Mid",
    recommendedFor: "Any Industry",
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#0ea5e9",
      accent: "#0ea5e9",
      bg: "#ffffff",
      text: "#0f172a",
      muted: "#64748b",
      border: "#e2e8f0",
      cardBg: "#f8fafc",
      sectionTitle: "#0f172a"
    }
  },
  {
    id: "executive-pro",
    name: "Executive Premium",
    description: "Gold-accented serif header with elegant section dividers. Premium executive presentation.",
    preview: "🏛️",
    family: "premium",
    layout: "standard",
    suggestedFont: "garamond",
    atsLabel: "ATS Friendly",
    category: "Executive",
    atsRating: 97,
    experienceLevel: "Executive",
    recommendedFor: "C-Suite & Board Members",
    suggestedColors: {
      primary: "#1a1f2e",
      secondary: "#c9a84c",
      accent: "#c9a84c",
      bg: "#ffffff",
      text: "#0f1520",
      muted: "#5a6478",
      border: "#dde1ea",
      cardBg: "#f7f8fb",
      sectionTitle: "#5a6478"
    }
  },
  {
    id: "engineering-clean",
    name: "Engineering Clean",
    description: "Built for software, AI, cloud and data engineers targeting top tech companies.",
    preview: "⚙️",
    family: "professional",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "ATS Optimized",
    category: "Software Engineer",
    atsRating: 98,
    experienceLevel: "Senior",
    recommendedFor: "Software & AI Engineers",
    legacy: true,
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#64748b",
      bg: "#ffffff",
      text: "#1e293b",
      muted: "#64748b",
      border: "#e2e8f0",
      cardBg: "#f1f5f9",
      sectionTitle: "#64748b"
    }
  },
  {
    id: "consulting-elite",
    name: "Consulting Elite",
    description: "Premium compact template for McKinsey, BCG, Bain, and Big 4 consulting roles.",
    preview: "📊",
    family: "compact",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "ATS Optimized",
    category: "Consulting",
    atsRating: 98,
    experienceLevel: "Senior",
    recommendedFor: "Consultants & Strategy Managers",
    legacy: true,
    suggestedColors: {
      primary: "#0d1b2a",
      secondary: "#1e293b",
      accent: "#1d4ed8",
      bg: "#ffffff",
      text: "#1e293b",
      muted: "#52637a",
      border: "#dde3ea",
      cardBg: "#f8fafc",
      sectionTitle: "#1e3a5f"
    }
  },
  {
    id: "product-manager",
    name: "Product Manager",
    description: "Compact PM template highlighting product ownership, KPIs, and launches.",
    preview: "📦",
    family: "compact",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "ATS Optimized",
    category: "Product Manager",
    atsRating: 98,
    experienceLevel: "Senior",
    recommendedFor: "Product & Program Managers",
    legacy: true,
    suggestedColors: {
      primary: "#0d1b2a",
      secondary: "#1e293b",
      accent: "#1d4ed8",
      bg: "#ffffff",
      text: "#1e293b",
      muted: "#52637a",
      border: "#dde3ea",
      cardBg: "#f0f4ff",
      sectionTitle: "#1d4ed8"
    }
  },
  {
    id: "creative-professional",
    name: "Creative Professional",
    description: "Two-column layout with boxed titles for designers and creatives.",
    preview: "🎨",
    family: "two-column",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "ATS Friendly",
    category: "Designer",
    atsRating: 95,
    experienceLevel: "Mid",
    recommendedFor: "Designers & Creatives",
    legacy: true,
    suggestedColors: {
      primary: "#111827",
      secondary: "#1f2937",
      accent: "#7c3aed",
      bg: "#ffffff",
      text: "#1f2937",
      muted: "#6b7280",
      border: "#e5e7eb",
      cardBg: "#ede9fe",
      sectionTitle: "#7c3aed"
    }
  },
  {
    id: "academic-cv",
    name: "Academic CV",
    description: "Scholarly multi-page CV for professors, researchers, and PhD candidates.",
    preview: "🎓",
    family: "serif",
    layout: "standard",
    suggestedFont: "garamond",
    atsLabel: "ATS Optimized",
    category: "Academic",
    atsRating: 98,
    experienceLevel: "Senior",
    recommendedFor: "Researchers & Faculty",
    legacy: true,
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#1e3a5f",
      bg: "#ffffff",
      text: "#1e293b",
      muted: "#475569",
      border: "#cbd5e1",
      cardBg: "#f8fafc",
      sectionTitle: "#1e3a5f"
    }
  },
  {
    id: "classic-serif",
    name: "Classic Serif",
    description: "Traditional serif design. Timeless appeal for legal, finance, government, and academia.",
    preview: "📜",
    family: "serif",
    layout: "standard",
    suggestedFont: "playfair",
    atsLabel: "ATS Friendly",
    category: "Professional",
    atsRating: 90,
    experienceLevel: "Senior",
    recommendedFor: "Legal & Finance Professionals",
    suggestedColors: COLOR_PALETTES[0].colors
  },
  {
    id: "tech-mono",
    name: "Tech Mono",
    description: "Monospace accents with a code-native engineering aesthetic.",
    preview: "💻",
    family: "compact",
    layout: "standard",
    suggestedFont: "sfmono",
    atsLabel: "Visual Layout",
    category: "Software Engineer",
    atsRating: 88,
    experienceLevel: "Mid",
    recommendedFor: "Backend & Systems Engineers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[1].colors
  },
  {
    id: "creative-burst",
    name: "Creative Burst",
    description: "Two-column sidebar with vibrant personality for creative portfolios.",
    preview: "🌈",
    family: "two-column",
    layout: "sidebar-right",
    suggestedFont: "jakarta",
    atsLabel: "Visual Layout",
    category: "Designer",
    atsRating: 84,
    experienceLevel: "Entry",
    recommendedFor: "Visual Designers & Artists",
    legacy: true,
    suggestedColors: COLOR_PALETTES[2].colors
  },
  {
    id: "compact-pro",
    name: "Compact",
    description: "Dense, information-rich layout. Maximum experience and skills in minimal space.",
    preview: "📋",
    family: "compact",
    layout: "compact",
    suggestedFont: "roboto",
    atsLabel: "ATS Friendly",
    category: "DevOps",
    atsRating: 89,
    experienceLevel: "Senior",
    recommendedFor: "Senior Engineers & Specialists",
    suggestedColors: COLOR_PALETTES[6].colors
  },
  {
    id: "corporate-blue",
    name: "Corporate Blue",
    description: "Trustworthy navy-blue design for corporate and advisory sectors.",
    preview: "🏢",
    family: "professional",
    layout: "standard",
    suggestedFont: "montserrat",
    atsLabel: "ATS Optimized",
    category: "Professional",
    atsRating: 94,
    experienceLevel: "Senior",
    recommendedFor: "Corporate Managers & Analysts",
    legacy: true,
    suggestedColors: COLOR_PALETTES[0].colors
  },
  {
    id: "minimal-edge",
    name: "Minimal Edge",
    description: "Ultra-clean layout with refined geometric lines.",
    preview: "◻️",
    family: "ats",
    layout: "standard",
    suggestedFont: "worksans",
    atsLabel: "ATS Optimized",
    category: "ATS Optimized",
    atsRating: 92,
    experienceLevel: "Entry",
    recommendedFor: "Early Career & Career Changers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[6].colors
  },
  {
    id: "banner-bold",
    name: "Banner Bold",
    description: "Full-width colored banner header. Strong visual impact for marketing and brand roles.",
    preview: "🚩",
    family: "banner",
    layout: "banner",
    suggestedFont: "montserrat",
    atsLabel: "Visual Layout",
    category: "Creative",
    atsRating: 82,
    experienceLevel: "Entry",
    recommendedFor: "Brand & Marketing Specialists",
    suggestedColors: COLOR_PALETTES[3].colors
  },
  {
    id: "sidebar-elegance",
    name: "Sidebar Elegance",
    description: "Refined right-side panel with balanced composition.",
    preview: "🎭",
    family: "two-column",
    layout: "sidebar-right",
    suggestedFont: "lato",
    atsLabel: "Visual Layout",
    category: "Designer",
    atsRating: 86,
    experienceLevel: "Mid",
    recommendedFor: "Product Designers & UI/UX",
    legacy: true,
    suggestedColors: COLOR_PALETTES[7].colors
  },
  {
    id: "gradient-flow",
    name: "Gradient Flow",
    description: "Modern two-column with gradient accents for tech resumes.",
    preview: "🌊",
    family: "two-column",
    layout: "two-column",
    suggestedFont: "jakarta",
    atsLabel: "ATS Friendly",
    category: "Software Engineer",
    atsRating: 91,
    experienceLevel: "Mid",
    recommendedFor: "AI/ML & Frontend Developers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[4].colors
  },
  {
    id: "academic-formal",
    name: "Academic Formal",
    description: "Formal serif layout for scholars and researchers.",
    preview: "🎓",
    family: "serif",
    layout: "standard",
    suggestedFont: "garamond",
    atsLabel: "ATS Optimized",
    category: "Academic",
    atsRating: 93,
    experienceLevel: "Senior",
    recommendedFor: "Academics & Researchers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[0].colors
  },
  {
    id: "startup-vibe",
    name: "Startup Vibe",
    description: "Energetic two-column design for high-growth tech startups.",
    preview: "🚀",
    family: "two-column",
    layout: "two-column",
    suggestedFont: "poppins",
    atsLabel: "ATS Friendly",
    category: "Creative",
    atsRating: 88,
    experienceLevel: "Entry",
    recommendedFor: "Startup Early Hires & Growth",
    legacy: true,
    suggestedColors: COLOR_PALETTES[1].colors
  },
  {
    id: "dark-elegance",
    name: "Dark Elegance",
    description: "Sophisticated dark header theme with bold contrast.",
    preview: "🌙",
    family: "banner",
    layout: "banner",
    suggestedFont: "inter",
    atsLabel: "Visual Layout",
    category: "Professional",
    atsRating: 85,
    experienceLevel: "Senior",
    recommendedFor: "Cybersecurity & Security Architects",
    legacy: true,
    suggestedColors: {
      primary: "#111827",
      secondary: "#1f2937",
      accent: "#374151",
      bg: "#ffffff",
      text: "#111827",
      muted: "#6b7280",
      border: "#e5e7eb",
      cardBg: "#f9fafb",
      sectionTitle: "#111827"
    }
  },
  {
    id: "timeline-pro",
    name: "Timeline",
    description: "Spacious single-column with gold-accent section dividers. Emphasizes career progression.",
    preview: "📅",
    family: "timeline",
    layout: "standard",
    suggestedFont: "lato",
    atsLabel: "ATS Friendly",
    category: "Software Engineer",
    atsRating: 87,
    experienceLevel: "Mid",
    recommendedFor: "Mid-to-Senior Engineers",
    suggestedColors: COLOR_PALETTES[8].colors
  },
  {
    id: "sidebar-left",
    name: "Left Sidebar",
    description: "Contact and skills in a left sidebar, experience in the main column. Quick-access layout.",
    preview: "\ud83d\udccb",
    family: "sidebar-left",
    layout: "standard",
    suggestedFont: "jakarta",
    atsLabel: "ATS Friendly",
    category: "Professional",
    atsRating: 95,
    experienceLevel: "Mid",
    recommendedFor: "Any Industry",
    suggestedColors: {
      primary: "#0f172a",
      secondary: "#1e293b",
      accent: "#2563eb",
      bg: "#ffffff",
      text: "#334155",
      muted: "#64748b",
      border: "#e2e8f0",
      cardBg: "#f8fafc",
      sectionTitle: "#0f172a"
    }
  },
  {
    id: "premium-slate",
    name: "Premium Slate",
    description: "Understated slate-gray palette for a refined corporate look.",
    preview: "💎",
    family: "professional",
    layout: "standard",
    suggestedFont: "worksans",
    atsLabel: "ATS Optimized",
    category: "Professional",
    atsRating: 92,
    experienceLevel: "Senior",
    recommendedFor: "Corporate Advisors & PMs",
    legacy: true,
    suggestedColors: COLOR_PALETTES[6].colors
  },
  {
    id: "nature-green",
    name: "Nature Green",
    description: "Earthy emerald tones for sustainability and biotech roles.",
    preview: "🌿",
    family: "two-column",
    layout: "two-column",
    suggestedFont: "robotoslab",
    atsLabel: "ATS Friendly",
    category: "Creative",
    atsRating: 88,
    experienceLevel: "Mid",
    recommendedFor: "Sustainability & Biotech Leaders",
    legacy: true,
    suggestedColors: COLOR_PALETTES[1].colors
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    description: "Warm amber and gold accents for top-tier executive presentation.",
    preview: "⭐",
    family: "banner",
    layout: "banner",
    suggestedFont: "fraunces",
    atsLabel: "Visual Layout",
    category: "Executive",
    atsRating: 90,
    experienceLevel: "Executive",
    recommendedFor: "Executive Leadership & Board Members",
    legacy: true,
    suggestedColors: COLOR_PALETTES[9].colors
  },
  {
    id: "swiss-design",
    name: "Swiss Design",
    description: "Grid-based layout inspired by Swiss typography.",
    preview: "📐",
    family: "compact",
    layout: "compact",
    suggestedFont: "inter",
    atsLabel: "ATS Friendly",
    category: "Modern",
    atsRating: 90,
    experienceLevel: "Senior",
    recommendedFor: "Architects & Systems Engineers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[10].colors
  },
  {
    id: "scientific",
    name: "Scientific",
    description: "Clean, citation-ready layout for research scientists and PhDs.",
    preview: "🔬",
    family: "serif",
    layout: "standard",
    suggestedFont: "robotoslab",
    atsLabel: "ATS Optimized",
    category: "Academic",
    atsRating: 95,
    experienceLevel: "Senior",
    recommendedFor: "Scientists & Researchers",
    legacy: true,
    suggestedColors: COLOR_PALETTES[0].colors
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    description: "Bold, visually-driven layout for designers and creative directors.",
    preview: "🖌️",
    family: "two-column",
    layout: "sidebar-right",
    suggestedFont: "poppins",
    atsLabel: "Visual Layout",
    category: "Designer",
    atsRating: 82,
    experienceLevel: "Entry",
    recommendedFor: "Artists & Creative Directors",
    legacy: true,
    suggestedColors: COLOR_PALETTES[2].colors
  },
];

export function getTemplateColors(templateId: string, paletteId?: string) {
  const template = TEMPLATES.find(t => t.id === templateId);
  if (paletteId) {
    const palette = COLOR_PALETTES.find(p => p.id === paletteId);
    if (palette) return palette.colors;
  }
  return template?.suggestedColors || COLOR_PALETTES[0].colors;
}
