"use client";
import { Resume, FormattedDescription, SocialLinks } from "./shared";

export function AcademicFormalPreview({ resume }: { resume: Resume }) {
  const navy = "#1e3a8a", ink = "#1f2937", muted = "#6b7280", line = "#d1d5db";
  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-6"><h2 className="mb-2 border-b pb-1 text-sm font-bold uppercase tracking-[0.12em]" style={{ color: navy, borderColor: `${navy}50` }}>{title}</h2>{children}</section>;
  return <div className="overflow-hidden rounded-lg bg-white shadow" style={{ fontFamily: "'EB Garamond', 'Times New Roman', Georgia, serif", color: ink }}>
    <div className="p-8">
      <header className="mb-7 text-center" style={{ borderBottom: `1.5px solid ${navy}40` }}>
        <h1 className="text-4xl font-bold leading-none" style={{ color: navy }}>{resume.name || "Your Name"}</h1>
        <p className="mt-2 text-lg italic" style={{ color: muted }}>{resume.title || "Professional Title"}</p>
        <div className="mx-auto mt-3 flex max-w-xl flex-wrap justify-center gap-x-4 gap-y-0.5 text-[12px]" style={{ color: muted }}>{resume.email && <span>{resume.email}</span>}{resume.phone && <span>{resume.phone}</span>}{resume.address && <span>{resume.address}</span>}{resume.pronouns && <span>{resume.pronouns}</span>}{resume.nationality && <span>{resume.nationality}</span>}</div>
        {resume.social && <div className="mt-2 mb-3"><SocialLinks social={resume.social} color={muted} size="xs" /></div>}
      </header>
      {resume.summary && <Section title="Abstract"><FormattedDescription text={resume.summary} color={ink} mutedColor={ink} size="sm" /></Section>}
      {resume.experience.length > 0 && <Section title="Appointments">{resume.experience.map(exp => <div key={exp.id} className="mb-4 last:mb-0"><div className="flex justify-between items-baseline gap-3"><div><h3 className="text-base font-bold" style={{ color: navy }}>{exp.position}</h3><p className="text-sm italic">{exp.company}{exp.location && `, ${exp.location}`}</p></div><span className="shrink-0 text-xs" style={{ color: muted }}>{exp.duration}</span></div>{exp.description && <div className="mt-1 pl-4" style={{ borderLeft: `1px solid ${line}` }}><FormattedDescription text={exp.description} color={navy} mutedColor={ink} /></div>}{exp.achievements && <FormattedDescription text={exp.achievements} color={navy} mutedColor={muted} />}</div>)}</Section>}
      {resume.education.length > 0 && <Section title="Education &amp; Degrees">{resume.education.map(edu => <div key={edu.id} className="mb-2 last:mb-0"><div className="flex justify-between gap-3"><div><h3 className="text-base font-bold" style={{ color: navy }}>{edu.school}</h3><p className="text-sm">{edu.degree}{edu.field ? ` in ${edu.field}` : ""}{edu.year && ` (${edu.year})`}</p></div>{edu.gpa && <span className="text-xs" style={{ color: muted }}>GPA: {edu.gpa}</span>}</div>{edu.honors && <p className="text-xs italic" style={{ color: muted }}>{edu.honors}</p>}{edu.minor && <p className="text-xs" style={{ color: muted }}>Minor: {edu.minor}</p>}</div>)}</Section>}
      {resume.skills.length > 0 && <Section title="Research Areas &amp; Competencies"><div className="grid grid-cols-2 gap-x-8 gap-y-2">{resume.skills.map(skill => <div key={skill.id} className="flex gap-1 items-baseline"><span className="text-sm font-semibold" style={{ color: navy }}>{skill.name}</span>{skill.category && <span className="text-xs italic" style={{ color: muted }}>· {skill.category}</span>}</div>)}</div></Section>}
      {resume.projects.length > 0 && <Section title="Publications &amp; Projects">{resume.projects.map(project => <div key={project.id} className="mb-3 last:mb-0"><div className="flex justify-between gap-3"><div><h3 className="text-base font-bold" style={{ color: navy }}>{project.name}</h3>{project.role && <p className="text-xs italic" style={{ color: muted }}>{project.role}</p>}</div><div className="shrink-0 text-xs text-right" style={{ color: muted }}>{project.startDate && <span>{project.startDate}{project.endDate && ` – ${project.endDate}`}</span>}{project.status && <p className="text-[10px] italic">{project.status}</p>}</div></div>{project.description && <div className="mt-1"><FormattedDescription text={project.description} color={navy} mutedColor={ink} /></div>}{project.tech && <p className="text-xs italic" style={{ color: muted }}>Methods: {project.tech}</p>}</div>)}</Section>}
      {resume.certifications.length > 0 && <Section title="Certifications &amp; Fellowships">{resume.certifications.map(cert => <p key={cert.id} className="text-sm mb-1"><span className="font-semibold" style={{ color: navy }}>{cert.name}</span>{cert.issuer && <span> — {cert.issuer}</span>}{cert.date && <span style={{ color: muted }}> ({cert.date})</span>}</p>)}</Section>}
      {resume.achievements.length > 0 && <Section title="Honors &amp; Awards">{resume.achievements.map(item => <p key={item.id} className="text-sm mb-1 pl-4" style={{ borderLeft: `1px solid ${navy}30` }}>{item.description}</p>)}</Section>}
      <div className="grid grid-cols-2 gap-6">
        {resume.languages.length > 0 && <Section title="Languages">{resume.languages.map(l => <p key={l.id} className="text-sm"><span className="font-semibold" style={{ color: navy }}>{l.name}</span><span className="italic" style={{ color: muted }}> ({l.proficiency})</span></p>)}</Section>}
        {resume.interests.length > 0 && <Section title="Scholarly Interests"><p className="text-sm italic" style={{ color: muted }}>{resume.interests.map(i => i.name).join(", ")}</p></Section>}
      </div>
      {resume.references.length > 0 && <Section title="References">{resume.references.map(ref => <div key={ref.id} className="mb-2"><p className="text-sm font-semibold" style={{ color: navy }}>{ref.name}</p><p className="text-xs italic" style={{ color: muted }}>{ref.position}{ref.company ? `, ${ref.company}` : ""}{ref.email ? ` · ${ref.email}` : ""}</p></div>)}</Section>}
    </div>
  </div>;
}
