"use client";
import { Resume, FormattedDescription, SocialLinks } from "./shared";

export function GradientFlowPreview({ resume }: { resume: Resume }) {
  const gradStart = "#0284c7", gradEnd = "#38bdf8", white = "#ffffff", ink = "#164e63", muted = "#64748b";
  const SideSection = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-5"><h2 className="mb-2 text-[10px] font-bold uppercase tracking-[0.18em] text-white/60">{title}</h2>{children}</section>;
  const MainSection = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-5"><div className="mb-3 flex items-center gap-2"><span className="inline-block h-2 w-2 rounded-full" style={{ backgroundColor: gradStart }} /><h2 className="text-xs font-extrabold uppercase tracking-[0.16em]" style={{ color: gradStart }}>{title}</h2></div>{children}</section>;
  return <div className="overflow-hidden rounded-lg bg-white shadow" style={{ fontFamily: "'Plus Jakarta Sans', 'Segoe UI', sans-serif", color: ink }}>
    <div className="flex min-h-[500px]">
      <div className="w-[220px] shrink-0 p-5 text-xs" style={{ background: `linear-gradient(180deg, ${gradStart}, ${gradEnd})`, color: white }}>
        <header className="mb-5"><h1 className="text-base font-black leading-tight">{resume.name || "Your Name"}</h1><p className="mt-0.5 text-xs text-white/80">{resume.title || "Professional Title"}</p></header>
        <SideSection title="Contact"><div className="space-y-1 text-[10px] text-white/90">{resume.email && <p>{resume.email}</p>}{resume.phone && <p>{resume.phone}</p>}{resume.address && <p>{resume.address}</p>}{resume.nationality && <p>{resume.nationality}</p>}</div>{resume.social && <div className="mt-2"><SocialLinks social={resume.social} color="#bae6fd" size="xs" /></div>}</SideSection>
        {resume.skills.length > 0 && <SideSection title="Skills">{resume.skills.map(skill => <div key={skill.id} className="mb-2"><div className="flex justify-between text-[10px] text-white/90"><span>{skill.name}</span><span className="text-white/60">{skill.level}</span></div><div className="mt-0.5 h-1.5 w-full overflow-hidden rounded-full bg-white/25"><div className="h-full rounded-full bg-white/80" style={{ width: skill.level === "Expert" ? "90%" : skill.level === "Advanced" ? "70%" : skill.level === "Intermediate" ? "50%" : "30%" }} /></div></div>)}</SideSection>}
        {resume.education.length > 0 && <SideSection title="Education">{resume.education.map(edu => <div key={edu.id} className="mb-2 last:mb-0"><p className="text-sm font-bold text-white/95">{edu.school}</p><p className="text-[10px] text-white/80">{edu.degree}{edu.field && `, ${edu.field}`}</p><p className="text-[9px] text-white/60">{edu.year}{edu.gpa && ` · GPA ${edu.gpa}`}</p></div>)}</SideSection>}
        {resume.certifications.length > 0 && <SideSection title="Certifications">{resume.certifications.map(cert => <p key={cert.id} className="mb-1 text-[10px] text-white/90">✓ {cert.name}{cert.issuer && <span className="text-white/60"> · {cert.issuer}</span>}</p>)}</SideSection>}
        {resume.languages.length > 0 && <SideSection title="Languages">{resume.languages.map(l => <p key={l.id} className="text-[10px] text-white/90"><b>{l.name}</b> <span className="text-white/60">· {l.proficiency}</span></p>)}</SideSection>}
      </div>
      <div className="flex-1 p-5 text-xs">
        {resume.summary && <div className="mb-5 rounded-xl p-3" style={{ backgroundColor: `${gradStart}08` }}><FormattedDescription text={resume.summary} color={gradStart} mutedColor={ink} size="sm" /></div>}
        {resume.experience.length > 0 && <MainSection title="Experience">{resume.experience.map(exp => <div key={exp.id} className="relative mb-4 pl-5 last:mb-0"><span className="absolute left-0 top-1.5 h-2.5 w-2.5 rounded-full border-2" style={{ borderColor: gradStart, backgroundColor: white }} /><span className="absolute bottom-0 left-[4.5px] top-4 w-0.5" style={{ backgroundColor: `${gradStart}20` }} /><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold" style={{ color: gradStart }}>{exp.position}</h3><p className="font-medium">{exp.company}{exp.location && ` · ${exp.location}`}</p></div><span className="shrink-0 text-[10px]" style={{ color: muted }}>{exp.duration}</span></div>{exp.description && <FormattedDescription text={exp.description} color={gradStart} mutedColor={ink} />}{exp.achievements && <FormattedDescription text={exp.achievements} color={gradEnd} mutedColor={ink} />}</div>)}</MainSection>}
        {resume.projects.length > 0 && <MainSection title="Projects">{resume.projects.map(project => <div key={project.id} className="mb-3 last:mb-0"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-bold" style={{ color: gradStart }}>{project.name}</h3><div className="flex gap-2 text-[10px]" style={{ color: muted }}>{project.startDate && <span>{project.startDate}{project.endDate && ` — ${project.endDate}`}</span>}{project.status && <span>{project.status}</span>}</div></div>{project.role && <p className="text-[10px] font-medium" style={{ color: gradStart }}>{project.role}{project.tech && <span> · {project.tech}</span>}</p>}{project.description && <FormattedDescription text={project.description} color={gradStart} mutedColor={ink} />}</div>)}</MainSection>}
        {resume.achievements.length > 0 && <MainSection title="Achievements">{resume.achievements.map(item => <p key={item.id} className="mb-1 flex items-start gap-1"><span style={{ color: gradStart }}>✦</span><span>{item.description}</span></p>)}</MainSection>}
        {resume.interests.length > 0 && <MainSection title="Interests"><p style={{ color: muted }}>{resume.interests.map(i => i.name).join(" · ")}</p></MainSection>}
        {resume.references.length > 0 && <MainSection title="References">{resume.references.map(ref => <p key={ref.id} className="mb-1"><b>{ref.name}</b>{ref.position && ` — ${ref.position}`}{ref.company && ` at ${ref.company}`}</p>)}</MainSection>}
      </div>
    </div>
  </div>;
}
