"use client";
import { Resume, FormattedDescription, SocialLinks } from "./shared";

export function MinimalEdgePreview({ resume }: { resume: Resume }) {
  const slate = "#475569", dark = "#0f172a", light = "#94a3b8", border = "#e2e8f0";
  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-7"><h2 className="mb-3 border-b pb-2 text-[10px] font-semibold uppercase tracking-[0.3em]" style={{ color: slate, borderColor: border }}>{title}</h2>{children}</section>;
  return <div className="overflow-hidden rounded-lg bg-white shadow" style={{ fontFamily: "'Work Sans', 'Segoe UI', sans-serif", color: slate }}>
    <div className="p-8">
      <header className="mb-9"><h1 className="text-4xl font-light leading-none tracking-tight" style={{ color: dark }}>{resume.name || "Your Name"}</h1><p className="mt-3 text-xs font-medium uppercase tracking-[0.28em]" style={{ color: slate }}>{resume.title || "Professional Title"}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-1 text-[10px]" style={{ color: light }}>{resume.email && <span>{resume.email}</span>}{resume.phone && <span>{resume.phone}</span>}{resume.address && <span>{resume.address}</span>}{resume.nationality && <span>{resume.nationality}</span>}</div>{resume.social && <div className="mt-2"><SocialLinks social={resume.social} color={light} size="xs" /></div>}</header>
      {resume.summary && <section className="mb-8 border-l pl-5" style={{ borderColor: slate }}><FormattedDescription text={resume.summary} color={slate} mutedColor={slate} size="sm" /></section>}
      {resume.experience.length > 0 && <Section title="Experience">{resume.experience.map(exp => <article key={exp.id} className="mb-6 last:mb-0"><div className="flex items-start justify-between gap-5"><div><h3 className="text-sm font-semibold" style={{ color: dark }}>{exp.position}</h3><p className="mt-0.5 text-xs">{exp.company}{exp.location && ` / ${exp.location}`}</p></div><span className="shrink-0 text-[10px] uppercase tracking-wider" style={{ color: light }}>{exp.duration}</span></div>{exp.description && <div className="mt-2"><FormattedDescription text={exp.description} color={slate} mutedColor={slate} /></div>}{exp.achievements && <FormattedDescription text={exp.achievements} color={slate} mutedColor={light} />}</article>)}</Section>}
      {resume.education.length > 0 && <Section title="Education"><div className="grid grid-cols-2 gap-x-8 gap-y-4">{resume.education.map(edu => <article key={edu.id}><div className="flex justify-between gap-2"><h3 className="text-sm font-semibold" style={{ color: dark }}>{edu.school}</h3><span className="text-[10px]" style={{ color: light }}>{edu.year}</span></div><p className="mt-1 text-xs">{edu.degree}{edu.field && ` / ${edu.field}`}</p>{edu.honors && <p className="text-[10px]" style={{ color: light }}>{edu.honors}</p>}</article>)}</div></Section>}
      {resume.skills.length > 0 && <Section title="Capabilities"><div className="grid grid-cols-3 gap-x-6 gap-y-3">{resume.skills.map(skill => <div key={skill.id} className="border-b pb-1.5" style={{ borderColor: border }}><p className="text-xs font-medium" style={{ color: dark }}>{skill.name}</p><p className="text-[9px] uppercase tracking-wider" style={{ color: light }}>{[skill.category, skill.level].filter(Boolean).join(" / ")}</p></div>)}</div></Section>}
      {resume.projects.length > 0 && <Section title="Selected Work"><div className="grid grid-cols-2 gap-6">{resume.projects.map(project => <article key={project.id}><div className="flex justify-between gap-2"><h3 className="text-sm font-semibold" style={{ color: dark }}>{project.name}</h3>{project.startDate && <span className="text-[9px]" style={{ color: light }}>{project.startDate}—{project.endDate || "Now"}</span>}</div>{project.role && <p className="mt-0.5 text-[10px] uppercase tracking-wider">{project.role}</p>}{project.description && <div className="mt-1"><FormattedDescription text={project.description} color={slate} mutedColor={slate} /></div>}{project.tech && <p className="mt-1 text-[10px]" style={{ color: light }}>{project.tech}</p>}</article>)}</div></Section>}
      {resume.certifications.length > 0 && <Section title="Credentials"><div className="grid grid-cols-2 gap-3">{resume.certifications.map(cert => <p key={cert.id} className="text-xs"><span className="font-medium" style={{ color: dark }}>{cert.name}</span>{cert.issuer && <span> / {cert.issuer}</span>}{cert.date && <span style={{ color: light }}> / {cert.date}</span>}</p>)}</div></Section>}
      {resume.achievements.length > 0 && <Section title="Recognition">{resume.achievements.map(item => <p key={item.id} className="mb-1 text-xs">{item.description}</p>)}</Section>}
      <div className="grid grid-cols-3 gap-7">
        {resume.languages.length > 0 && <Section title="Languages">{resume.languages.map(l => <p key={l.id} className="text-xs">{l.name} <span style={{ color: light }}>/ {l.proficiency}</span></p>)}</Section>}
        {resume.interests.length > 0 && <Section title="Interests"><p className="text-xs">{resume.interests.map(i => i.name).join(" / ")}</p></Section>}
        {resume.references.length > 0 && <Section title="References">{resume.references.map(ref => <p key={ref.id} className="mb-1 text-xs"><span style={{ color: dark }}>{ref.name}</span>{ref.company && ` / ${ref.company}`}</p>)}</Section>}
      </div>
    </div>
  </div>;
}
