export * from './interfaces';
export * from './providers';
export { SeatManager } from './seat-manager';
export * from './services';
export * from './types';
export { UsageLimitService } from './usage-limit.service';
export { WebhookHandler } from './webhook-handler';

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    tier: 'free' as const,
    description: 'Get started with basic career tools',
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: 'usd',
    features: ['1 resume', '10 claims', '1 passport publication', '50 MB storage'],
    limits: {
      maxResumes: 1,
      maxClaims: 10,
      maxPassportPublications: 1,
      maxAIRequestsPerMonth: 0,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 0,
      maxStorageMB: 50,
      maxTeamWorkspaces: 0,
      hasAIAssistant: false,
      hasATSKeywords: false,
      hasAdvancedAnalytics: false,
      hasApiAccess: false,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 0,
  },
  {
    id: 'pro',
    name: 'Pro',
    tier: 'pro' as const,
    description: 'For professionals building their career',
    monthlyPrice: 1200,
    yearlyPrice: 12000,
    currency: 'usd',
    features: [
      '10 resumes',
      '100 claims',
      '5 passport publications',
      '100 AI requests/month',
      '500 MB storage',
      'AI assistant',
      'ATS keyword optimization',
    ],
    limits: {
      maxResumes: 10,
      maxClaims: 100,
      maxPassportPublications: 5,
      maxAIRequestsPerMonth: 100,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 1,
      maxStorageMB: 500,
      maxTeamWorkspaces: 0,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: false,
      hasApiAccess: false,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'premium',
    name: 'Premium',
    tier: 'premium' as const,
    description: 'Serious career management power',
    monthlyPrice: 2900,
    yearlyPrice: 29000,
    currency: 'usd',
    features: [
      '50 resumes',
      '500 claims',
      '25 passport publications',
      '500 AI requests/month',
      '2 GB storage',
      'Advanced analytics',
      'API access',
    ],
    limits: {
      maxResumes: 50,
      maxClaims: 500,
      maxPassportPublications: 25,
      maxAIRequestsPerMonth: 500,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 5,
      maxStorageMB: 2000,
      maxTeamWorkspaces: 0,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'recruiter_pro',
    name: 'Recruiter Pro',
    tier: 'recruiter_pro' as const,
    description: 'For solo recruiters',
    monthlyPrice: 4900,
    yearlyPrice: 49000,
    currency: 'usd',
    features: [
      '100 resumes',
      '1000 claims',
      '100 passport publications',
      '500 AI requests/month',
      '5 GB storage',
      '1 recruiter seat',
      'API access',
      'Priority support',
    ],
    limits: {
      maxResumes: 100,
      maxClaims: 1000,
      maxPassportPublications: 100,
      maxAIRequestsPerMonth: 500,
      maxRecruiterSeats: 1,
      maxOrganizationMembers: 10,
      maxStorageMB: 5000,
      maxTeamWorkspaces: 1,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: false,
      hasPrioritySupport: true,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'recruiter_team',
    name: 'Recruiter Team',
    tier: 'recruiter_team' as const,
    description: 'For recruiting teams',
    monthlyPrice: 14900,
    yearlyPrice: 149000,
    currency: 'usd',
    features: [
      '500 resumes',
      '5000 claims',
      '500 passport publications',
      '2000 AI requests/month',
      '20 GB storage',
      '10 recruiter seats',
      'SSO',
      'Custom branding',
      'Priority support',
    ],
    limits: {
      maxResumes: 500,
      maxClaims: 5000,
      maxPassportPublications: 500,
      maxAIRequestsPerMonth: 2000,
      maxRecruiterSeats: 10,
      maxOrganizationMembers: 50,
      maxStorageMB: 20000,
      maxTeamWorkspaces: 5,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: true,
      hasPrioritySupport: true,
      hasCustomBranding: true,
    },
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'business',
    name: 'Business',
    tier: 'business' as const,
    description: 'For growing businesses',
    monthlyPrice: 7900,
    yearlyPrice: 79000,
    currency: 'usd',
    features: [
      '200 resumes',
      '2000 claims',
      '200 passport publications',
      '1000 AI requests/month',
      '10 GB storage',
      '5 team seats',
      'SSO',
      'Custom branding',
      'Priority support',
    ],
    limits: {
      maxResumes: 200,
      maxClaims: 2000,
      maxPassportPublications: 200,
      maxAIRequestsPerMonth: 1000,
      maxRecruiterSeats: 5,
      maxOrganizationMembers: 25,
      maxStorageMB: 10000,
      maxTeamWorkspaces: 3,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: true,
      hasPrioritySupport: true,
      hasCustomBranding: true,
    },
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tier: 'enterprise' as const,
    description: 'Organizational career intelligence',
    monthlyPrice: 19900,
    yearlyPrice: 199000,
    currency: 'usd',
    features: [
      'Unlimited resumes',
      'Unlimited claims',
      'Unlimited publications',
      '10,000 AI requests/month',
      '100 GB storage',
      'SSO & custom branding',
      'Priority support',
    ],
    limits: {
      maxResumes: 9999,
      maxClaims: 99999,
      maxPassportPublications: 9999,
      maxAIRequestsPerMonth: 10000,
      maxRecruiterSeats: 999,
      maxOrganizationMembers: 9999,
      maxStorageMB: 100000,
      maxTeamWorkspaces: 999,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: true,
      hasPrioritySupport: true,
      hasCustomBranding: true,
    },
    isActive: true,
    sortOrder: 6,
  },
] as const;
