export * from './interfaces';
export * from './providers';
export * from './services';
export * from './types';

export const PLANS = [
  {
    id: 'free',
    name: 'Free',
    tier: 'free',
    description: 'Get started with basic career tools',
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: 'usd',
    features: ['1 resume', '10 claims', '1 passport publication', '50 MB storage'],
    limits: {
      maxResumes: 1,
      maxClaims: 10,
      maxPassportPublications: 1,
      maxAIRequestsPerMonth: 0,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 0,
      maxStorageMB: 50,
      maxTeamWorkspaces: 0,
      hasAIAssistant: false,
      hasATSKeywords: false,
      hasAdvancedAnalytics: false,
      hasApiAccess: false,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 0,
  },
  {
    id: 'pro',
    name: 'Pro',
    tier: 'pro',
    description: 'For professionals building their career',
    monthlyPrice: 1200,
    yearlyPrice: 12000,
    currency: 'usd',
    features: [
      '10 resumes',
      '100 claims',
      '5 passport publications',
      '100 AI requests/month',
      '500 MB storage',
      'AI assistant',
      'ATS keyword optimization',
    ],
    limits: {
      maxResumes: 10,
      maxClaims: 100,
      maxPassportPublications: 5,
      maxAIRequestsPerMonth: 100,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 1,
      maxStorageMB: 500,
      maxTeamWorkspaces: 0,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: false,
      hasApiAccess: false,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'premium',
    name: 'Premium',
    tier: 'premium',
    description: 'Serious career management power',
    monthlyPrice: 2900,
    yearlyPrice: 29000,
    currency: 'usd',
    features: [
      '50 resumes',
      '500 claims',
      '25 passport publications',
      '500 AI requests/month',
      '2 GB storage',
      'Advanced analytics',
      'API access',
    ],
    limits: {
      maxResumes: 50,
      maxClaims: 500,
      maxPassportPublications: 25,
      maxAIRequestsPerMonth: 500,
      maxRecruiterSeats: 0,
      maxOrganizationMembers: 5,
      maxStorageMB: 2000,
      maxTeamWorkspaces: 0,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: false,
      hasPrioritySupport: false,
      hasCustomBranding: false,
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tier: 'enterprise',
    description: 'Organizational career intelligence',
    monthlyPrice: 9900,
    yearlyPrice: 99000,
    currency: 'usd',
    features: [
      'Unlimited resumes',
      'Unlimited claims',
      'Unlimited publications',
      '10,000 AI requests/month',
      '100 GB storage',
      'SSO & custom branding',
      'Priority support',
    ],
    limits: {
      maxResumes: 9999,
      maxClaims: 99999,
      maxPassportPublications: 9999,
      maxAIRequestsPerMonth: 10000,
      maxRecruiterSeats: 999,
      maxOrganizationMembers: 9999,
      maxStorageMB: 100000,
      maxTeamWorkspaces: 999,
      hasAIAssistant: true,
      hasATSKeywords: true,
      hasAdvancedAnalytics: true,
      hasApiAccess: true,
      hasSso: true,
      hasPrioritySupport: true,
      hasCustomBranding: true,
    },
    isActive: true,
    sortOrder: 3,
  },
] as const;
